kind: Service
apiVersion: v1
metadata:
  name: player-r2dbc
spec:
  selector:
    app: player-r2dbc
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30002
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-r2dbc
spec:
  selector:
      matchLabels:
        app: player-r2dbc
        tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: player-r2dbc
        tier: backend
    spec:
      containers:
        - name: player-r2dbc
          image: reactive/player-r2dbc:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 40
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 100
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 1